\i dropTables.sql
\i createVehicleStatus.sql
\i createTables.sql
\i insertDataVehicleType.sql
\i insertDataVehicles.sql
\i insertDataCustomer.sql
\i insertDataReservations.sql
\i insertDataRents.sql
\i insertDataReturns.sql